pipeline {
  agent any
  options {
    disableConcurrentBuilds()
  }
  stages {
    stage('Build') {
        agent {
            docker {
                image 'node:12.16.3'
            }
        }
        environment {
            API_URL = 'https://zubr.club'
            HOME = '.'
            npm_config_cache = 'npm-cache'
        }
        steps {
            script {
                env.BRANCH = GIT_BRANCH.replace("origin/", "")
            }
            echo "${env.BRANCH}"
            sh 'npm ci'
            sh 'npm run test'
            sh 'npm run lint'
            sh 'npm run web:prod'

            stash includes: 'dist/apps/zubr-web/**', name: 'output'
            stash includes: 'infrastructure/*', name: 'infra'
        }
    }
    stage('Deploy') {
        environment {
            FRONTEND_HOST = credentials('FRONTEND_HOST')
            API_URL       = credentials('API_URL')
        }
        steps {
            unstash 'infra'
            unstash 'output'
            writeFile file: 'dist/apps/zubr-web/assets/env/env.js', text: """
(function(window) {
    window['env'] = window['env'] || {};

    // default Environment variables
    window['env']['apiUrl'] = '$API_URL';
})(this);c
"""
            ansiblePlaybook(
               playbook: "infrastructure/ansistrano_${env.BRANCH}_deploy.yml",
               inventory: "$FRONTEND_HOST,",
               credentialsId: "SSH_PRIVATE_KEY",
               hostKeyChecking: false
           )
        }
    }
  }
}

